# Project: keyboard
# Makefile created by Dev-C++ 5.3.0.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../audio.o ../console_draw2.o ../kb_input2.o ../keyboard.o $(RES)
LINKOBJ  = ../audio.o ../console_draw2.o ../kb_input2.o ../keyboard.o $(RES)
LIBS     = -L"C:/Users/htchen/Desktop/Dev-Cpp 5.3.0.3 MinGW 4.7.0 Portable/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -lwinmm 
INCS     = -I"C:/Users/htchen/Desktop/Dev-Cpp 5.3.0.3 MinGW 4.7.0 Portable/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Users/htchen/Desktop/Dev-Cpp 5.3.0.3 MinGW 4.7.0 Portable/Dev-Cpp/MinGW32/include"
BIN      = keyboard.exe
CXXFLAGS = $(CXXINCS)  -Wall
CFLAGS   = $(INCS)  -Wall
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../audio.o: ../audio.c
	$(CC) -c ../audio.c -o ../audio.o $(CFLAGS)

../console_draw2.o: ../console_draw2.c
	$(CC) -c ../console_draw2.c -o ../console_draw2.o $(CFLAGS)

../kb_input2.o: ../kb_input2.c
	$(CC) -c ../kb_input2.c -o ../kb_input2.o $(CFLAGS)

../keyboard.o: ../keyboard.c
	$(CC) -c ../keyboard.c -o ../keyboard.o $(CFLAGS)
